AWSTemplateFormatVersion: "2010-09-09"
Description: "Task Manager Deployment Infrastructure"

Parameters:
  BaseDomain:
    Type: String
    Description: "Base domain for deployments"
  HostedZoneId:
    Type: String
    Description: "Route53 Hosted Zone ID"
  EC2IP:
    Type: String
    Description: "EC2 Instance IP Address"
  DeploymentBucket:
    Type: String
    Description: "S3 Bucket for Lambda deployment packages"

Resources:
  # API Gateway
  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: TaskManagerDeploymentAPI
      EndpointConfiguration:
        Types:
          - REGIONAL

  # API Resource
  DeploymentResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: deploy

  # API Methods
  DeploymentMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: POST
      ResourceId: !Ref DeploymentResource
      RestApiId: !Ref ApiGateway
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations
          - LambdaArn: !GetAtt DeployAppFunction.Arn

  OptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: OPTIONS
      ResourceId: !Ref DeploymentResource
      RestApiId: !Ref ApiGateway
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: "200"
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'https://www.pmtracker.io'"
              method.response.header.Access-Control-Allow-Methods: "'POST,OPTIONS'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: "200"
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Headers: true

  # API Deployment
  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: 
      - DeploymentMethod
      - OptionsMethod
    Properties:
      RestApiId: !Ref ApiGateway
      StageName: prod

  # Lambda Functions
  CreateSubdomainFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref DeploymentBucket
        S3Key: lambda/create-subdomain.zip
      Environment:
        Variables:
          HOSTED_ZONE_ID: !Ref HostedZoneId
          BASE_DOMAIN: !Ref BaseDomain
          EC2_IP: !Ref EC2IP

  DeployAppFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref DeploymentBucket
        S3Key: lambda/deploy-app.zip
      Environment:
        Variables:
          GITHUB_REPO_URL: "git@github.com:alehstrunevskiy/task-manager.git"
          DEPLOY_PATH: "/var/www/html"

  NotificationFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref DeploymentBucket
        S3Key: lambda/send-notification.zip
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref NotificationTopic

  # IAM Role
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  # SNS Topic
  NotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: TaskManagerDeployment

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod/deploy"